language: android
# Setting java 1.8 
jdk:
  - oraclejdk8
sudo: false
#cache:
#  directories:
#    - ${TRAVIS_BUILD_DIR}/gradle/caches/
#    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

env:
  matrix:

    - EMULATOR_API_LEVEL=24 ABI_TAG=android      #ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-24      # stalling
    - EMULATOR_API_LEVEL=24 ABI_TAG=android-wear #ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-wear-24 # stalling
    - EMULATOR_API_LEVEL=23 ABI_TAG=android      #ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-23      # stalling
    - EMULATOR_API_LEVEL=23 ABI_TAG=android-wear #ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-wear-23
    - EMULATOR_API_LEVEL=22 ABI_TAG=android      #ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-22
    - EMULATOR_API_LEVEL=22 ABI_TAG=android-wear #ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-wear-22
    - EMULATOR_API_LEVEL=21 ABI_TAG=android      #ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-21
    - EMULATOR_API_LEVEL=21 ABI_TAG=android-wear #ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-wear-21
    - EMULATOR_API_LEVEL=20 ABI_TAG=android-wear #ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-wear-20
    - EMULATOR_API_LEVEL=19 ABI_TAG=android      #ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-19
    - EMULATOR_API_LEVEL=18 ABI_TAG=android      #ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-18
    - EMULATOR_API_LEVEL=17 ABI_TAG=android      #ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-17
    - EMULATOR_API_LEVEL=16 ABI_TAG=android      #ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-16
    - EMULATOR_API_LEVEL=15 ABI_TAG=android      #ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-15
    - EMULATOR_API_LEVEL=14 ABI_TAG=android      #ANDROID_EMULATOR_IMAGE=sys-img-armeabi-v7a-android-14

  global:
    - ANDROID_API_LEVEL=24
    - ANDROID_BUILD_TOOLS_VERSION=24.0.2
    - ADB_INSTALL_TIMEOUT=20 # wait up to 20 minutes for adb to connect to emulator (2 minutes by default)
    - ANDROID_ABI=armeabi-v7a

    - TERM=dumb # Initiating clean Gradle output    
    - GRADLE_OPTS="-Xmx2048m" # Amount of memory granted to Gradle JVM
    
android:
  components:
    # Base components 
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools 25.1.x
    - platform-tools   
    
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION # get the build tools version to build the project
    - android-$ANDROID_API_LEVEL # get the android sdk version to build the project
    - android-$EMULATOR_API_LEVEL # get the android sdk version for the emulator

    # Get the latest version of additional components
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services

    # Specify the needed emulator
    - sys-img-armeabi-v7a-${ABI_TAG}-${EMULATOR_API_LEVEL}
    #- $ANDROID_EMULATOR_IMAGE

# Emulator Management: Create, Start and Wait
before_install:
  - echo $ANDROID_TARGET 
  - echo $ANDROID_ABI
  - echo sys-img-armeabi-v7a-${ABI_TAG}-${EMULATOR_API_LEVEL}
  - android list targets
  - android list sdk --no-ui --all --extended
before_script:
  - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ABI_TAG
  - emulator -avd test -partition-size 1024 -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
after_script:
  - cat /home/travis/build/Countly/countly-sdk-android/sdk-messaging/build/outputs/lint-results-debug.xml
  - cat /home/travis/build/Countly/countly-sdk-android/sdk/build/reports/androidTests/connected/index.html